name: WakaTime
on:
  # Schedule updates (each hour)
  schedule: [{ cron: '0 * * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: oderahub
          template: classic
          base: ''
          config_timezone: Africa/Lagos
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_days: 7
