name: Stargazers
on:
  # Schedule updates (each hour)
  schedule: [{ cron: '0 * * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: oderahub
          template: classic
          base: ''
          config_timezone: Africa/Lagos
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
