name: Activity
on:
  # Schedule updates (each hour)
  schedule: [{ cron: '0 * * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: oderahub
          template: classic
          base: ''
          config_timezone: Africa/Lagos
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes
